# Generated by Django 5.1.6 on 2025-03-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plearnApp', '0002_alter_task_completed_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='name',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('0%', 'Not started'), ('25%', 'Just started'), ('50%', 'Half-way done'), ('75%', 'Almost done'), ('100%', 'Completed')], default='0%', max_length=4),
        ),
    ]
