# Generated by Django 5.1.6 on 2025-03-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plearnApp', '0005_goal_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='title',
            new_name='milestone',
        ),
    ]
